import { NextRequest, NextResponse } from 'next/server';

function fmtM(v: number): string {
  if (!v) return '—';
  if (v >= 1e12) return `$${(v / 1e12).toFixed(2)}T`;
  if (v >= 1e9) return `$${(v / 1e9).toFixed(2)}B`;
  if (v >= 1e6) return `$${(v / 1e6).toFixed(1)}M`;
  if (v >= 1e3) return `$${(v / 1e3).toFixed(1)}K`;
  return `$${v.toFixed(0)}`;
}

function rt(content: string) {
  return [{ type: 'text', text: { content } }];
}

function tableRow(cells: string[]) {
  return {
    type: 'table_row',
    table_row: { cells: cells.map(c => [{ type: 'text', text: { content: c } }]) },
  };
}

export async function POST(req: NextRequest) {
  const { token, parentPageId, input, result, competitors } = await req.json();
  if (!token || !parentPageId) {
    return NextResponse.json({ error: 'token and parentPageId required' }, { status: 400 });
  }

  const competitorRows = competitors.map((c: {
    name: string; stage: string; estimated_revenue: number;
    market_share_pct: number; hq: string;
  }) => tableRow([c.name, c.stage, fmtM(c.estimated_revenue), `${c.market_share_pct.toFixed(1)}%`, c.hq]));

  const stepRows = result.steps.map((s: { label: string; value: number; unit: string; rationale: string }) =>
    tableRow([s.label, `${s.value.toLocaleString()} ${s.unit}`, s.rationale])
  );

  const blocks = [
    {
      type: 'callout',
      callout: {
        rich_text: rt(`${input.market} · ${input.geography} · ${input.year} · ${result.methodology}`),
        icon: { type: 'emoji', emoji: '🌐' },
        color: 'blue_background',
      },
    },
    { type: 'heading_2', heading_2: { rich_text: rt('Market Sizing') } },
    {
      type: 'table',
      table: {
        table_width: 2,
        has_column_header: true,
        has_row_header: false,
        children: [
          tableRow(['Metric', 'Value']),
          tableRow(['TAM (Total Addressable Market)', fmtM(result.tam)]),
          tableRow(['SAM (Serviceable Addressable Market)', fmtM(result.sam)]),
          tableRow(['SOM (Serviceable Obtainable Market)', fmtM(result.som)]),
        ],
      },
    },
    { type: 'heading_2', heading_2: { rich_text: rt('Analyst Narrative') } },
    { type: 'paragraph', paragraph: { rich_text: rt(result.narrative) } },
    { type: 'heading_2', heading_2: { rich_text: rt('Assumptions') } },
    {
      type: 'table',
      table: {
        table_width: 3,
        has_column_header: true,
        has_row_header: false,
        children: [tableRow(['Assumption', 'Value', 'Rationale']), ...stepRows],
      },
    },
    ...(competitors.length > 0
      ? [
          { type: 'heading_2', heading_2: { rich_text: rt('Competitor Landscape') } },
          {
            type: 'table',
            table: {
              table_width: 5,
              has_column_header: true,
              has_row_header: false,
              children: [tableRow(['Company', 'Stage', 'Est. Revenue', 'Mkt Share', 'HQ']), ...competitorRows],
            },
          },
        ]
      : []),
    { type: 'divider', divider: {} },
    {
      type: 'paragraph',
      paragraph: {
        rich_text: [{ type: 'text', text: { content: 'Generated by Atlas Market Intelligence Engine' }, annotations: { italic: true, color: 'gray' } }],
      },
    },
  ];

  const notionRes = await fetch('https://api.notion.com/v1/pages', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      'Notion-Version': '2022-06-28',
    },
    body: JSON.stringify({
      parent: { page_id: parentPageId },
      properties: {
        title: { title: rt(`Market Report: ${input.market} (${input.year})`) },
      },
      children: blocks,
    }),
  });

  if (!notionRes.ok) {
    const err = await notionRes.text();
    return NextResponse.json({ error: err }, { status: notionRes.status });
  }

  const data = await notionRes.json();
  return NextResponse.json({ url: data.url, id: data.id });
}
