import { NextRequest, NextResponse } from 'next/server';

function fmtM(v: number): string {
  if (!v) return '—';
  if (v >= 1e12) return `$${(v / 1e12).toFixed(2)}T`;
  if (v >= 1e9) return `$${(v / 1e9).toFixed(2)}B`;
  if (v >= 1e6) return `$${(v / 1e6).toFixed(1)}M`;
  if (v >= 1e3) return `$${(v / 1e3).toFixed(1)}K`;
  return `$${v.toFixed(0)}`;
}

export async function POST(req: NextRequest) {
  const { webhookUrl, input, result, competitors } = await req.json();
  if (!webhookUrl) return NextResponse.json({ error: 'webhookUrl required' }, { status: 400 });

  const topComps = (competitors as { name: string; stage: string; estimated_revenue: number }[])
    .slice(0, 5)
    .map(c => `• *${c.name}* (${c.stage}) — ${fmtM(c.estimated_revenue)} est. revenue`)
    .join('\n');

  const blocks = [
    {
      type: 'header',
      text: { type: 'plain_text', text: `📊 Market Report: ${input.market}` },
    },
    {
      type: 'section',
      fields: [
        { type: 'mrkdwn', text: `*Geography*\n${input.geography}` },
        { type: 'mrkdwn', text: `*Year*\n${input.year}` },
        { type: 'mrkdwn', text: `*Methodology*\n${result.methodology}` },
      ],
    },
    { type: 'divider' },
    {
      type: 'section',
      fields: [
        { type: 'mrkdwn', text: `*TAM*\n${fmtM(result.tam)}` },
        { type: 'mrkdwn', text: `*SAM*\n${fmtM(result.sam)}` },
        { type: 'mrkdwn', text: `*SOM*\n${fmtM(result.som)}` },
      ],
    },
    { type: 'divider' },
    {
      type: 'section',
      text: { type: 'mrkdwn', text: `*Analyst View*\n${result.narrative}` },
    },
    ...(competitors.length > 0
      ? [
          { type: 'divider' },
          {
            type: 'section',
            text: { type: 'mrkdwn', text: `*Top Competitors*\n${topComps}` },
          },
        ]
      : []),
    { type: 'divider' },
    {
      type: 'context',
      elements: [{ type: 'mrkdwn', text: '_Generated by Atlas Market Intelligence Engine_' }],
    },
  ];

  const slackRes = await fetch(webhookUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ blocks }),
  });

  if (!slackRes.ok) {
    return NextResponse.json({ error: 'Slack webhook failed' }, { status: 500 });
  }

  return NextResponse.json({ success: true });
}
